steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/tracula-image', '.' ]

images:
  - 'gcr.io/$PROJECT_ID/tracula-image'
    
# DEPLOY
# - name: 'gcr.io/cloud-builders/gcloud'
#    id: 'function-deploy'
    # Not yet - args: ['functions', 'deploy', 'daily', '--runtime=go113', '--trigger-http', '--source=./', '--entry-point=ProcessDaily', '--env-vars-file=.env.yaml']
